const modal = document.querySelector('#calculator-modal');
const content = document.querySelector('#calculator-content');
const rupees = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(Math.max(0, value));

const templates = {
  budget: () => `<section class="calculator"><h2>Monthly Budget Planner</h2><p class="intro">Find your monthly balance and a simple saving target.</p><form class="calc-form" data-calculator="budget"><div class="field"><label>Monthly take-home income (â‚¹)</label><input required type="number" name="income" min="0" placeholder="50000" /></div><div class="field"><label>Rent / housing (â‚¹)</label><input required type="number" name="housing" min="0" placeholder="15000" /></div><div class="field"><label>Food & groceries (â‚¹)</label><input required type="number" name="food" min="0" placeholder="7000" /></div><div class="field"><label>Commute (â‚¹)</label><input required type="number" name="commute" min="0" placeholder="3000" /></div><div class="field"><label>EMIs & bills (â‚¹)</label><input required type="number" name="bills" min="0" placeholder="8000" /></div><div class="field"><label>Other spending (â‚¹)</label><input required type="number" name="other" min="0" placeholder="5000" /></div><button class="calculate">See my monthly picture</button></form><div class="result"></div></section>`,
  commute: () => `<section class="calculator"><h2>Commute Cost Calculator</h2><p class="intro">See the true monthly cost of your daily journey.</p><form class="calc-form" data-calculator="commute"><div class="field"><label>One-way distance (km)</label><input required type="number" name="distance" min="0" step="0.1" placeholder="12" /></div><div class="field"><label>Working days each month</label><input required type="number" name="days" min="1" max="31" placeholder="22" /></div><div class="field full"><label>How do you commute?</label><select name="mode"><option value="bike">Bike / scooter</option><option value="car">Car</option><option value="metro">Metro</option><option value="bus">Bus</option><option value="cab">Cab / auto</option></select></div><div class="field full"><label>Cost per km (â‚¹) â€” edit this if you know it</label><input required type="number" name="rate" min="0" step="0.1" value="2.5" /></div><button class="calculate">Calculate my commute cost</button></form><div class="result"></div></section>`,
  emi: () => `<section class="calculator"><h2>EMI & Loan Calculator</h2><p class="intro">Understand your monthly EMI and the complete cost of borrowing.</p><form class="calc-form" data-calculator="emi"><div class="field"><label>Loan amount (â‚¹)</label><input required type="number" name="principal" min="1" placeholder="500000" /></div><div class="field"><label>Annual interest rate (%)</label><input required type="number" name="rate" min="0" step="0.1" placeholder="10.5" /></div><div class="field full"><label>Loan period (years)</label><input required type="number" name="years" min="1" step="1" placeholder="5" /></div><button class="calculate">Calculate my EMI</button></form><div class="result"></div></section>`
};

document.querySelectorAll('[data-tool]').forEach(button => button.addEventListener('click', () => { content.innerHTML = templates[button.dataset.tool](); modal.showModal(); }));
document.querySelector('.close-modal').addEventListener('click', () => modal.close());
modal.addEventListener('click', event => { if (event.target === modal) modal.close(); });

content.addEventListener('submit', event => {
  event.preventDefault();
  const form = event.target; const data = Object.fromEntries(new FormData(form)); const result = form.parentElement.querySelector('.result');
  if (form.dataset.calculator === 'budget') { const spent = ['housing','food','commute','bills','other'].reduce((sum, key) => sum + Number(data[key]), 0); const balance = Number(data.income) - spent; const target = Math.max(0, Number(data.income) * .2); result.innerHTML = `<small>YOUR MONTHLY BALANCE</small><strong>${rupees(balance)}</strong><p>${balance >= target ? `Great startâ€”you are above a 20% saving target of ${rupees(target)}.` : balance >= 0 ? `You have ${rupees(balance)} left. A 20% saving target would be ${rupees(target)}.` : `Your planned spending is ${rupees(Math.abs(balance))} above your income. Start by reviewing flexible costs.`}</p>`; }
  if (form.dataset.calculator === 'commute') { const defaults = { bike: 2.5, car: 8, metro: 3, bus: 2, cab: 15 }; if (event.submitter === form.querySelector('button') && data.rate === '2.5' && data.mode !== 'bike') form.rate.value = defaults[data.mode]; const rate = Number(form.rate.value); const monthly = Number(data.distance) * 2 * Number(data.days) * rate; result.innerHTML = `<small>ESTIMATED MONTHLY COMMUTE COST</small><strong>${rupees(monthly)}</strong><p>That is about ${rupees(monthly / Number(data.days))} per workday and ${rupees(monthly * 12)} a year. This is an estimateâ€”fuel, fares, and maintenance vary by city.</p>`; }
  if (form.dataset.calculator === 'emi') { const p=Number(data.principal), n=Number(data.years)*12, r=Number(data.rate)/1200; const emi=r ? p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1) : p/n; const interest=emi*n-p; result.innerHTML = `<small>YOUR ESTIMATED MONTHLY EMI</small><strong>${rupees(emi)}</strong><p>Total repayment: ${rupees(emi*n)}. Total interest: ${rupees(interest)}. Paying even a little extra early can reduce this interest.</p>`; }
  result.classList.add('show');
});

document.querySelector('#year').textContent = new Date().getFullYear();

